name: Push to GHCR

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: docker build
        run: docker build -t ghcr.io/viranch/tv .

      - name: docker login
        uses: docker/login-action@v1 
        with:
          username: viranch
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker push
        run: docker push ghcr.io/viranch/tv
